### ISSUE TITLE
The Massive Todo 

### ISSUE THREAD

**Issue by jdorfman** [curiefense/docs#1]
## Add

- [ ] [Algolia (Search)](https://docusaurus.io/docs/search#using-algolia-docsearch)
- [x] [Netlify](https://docusaurus.io/docs/deployment#deploying-to-netlify)
- [ ] Redirects from old docs
- [x] Favicon
- [x] Versions
 - [ ] Dropdown
    - [x] `1.0.0`
    - [x] `1.3.0`
    - [ ] `1.4.0`
- [ ] Insert the following code in the <head> section of your pages:
```
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">
```

## Update

- [ ] CSS
- [ ] README
- [ ] Footer
- [ ] Nav

## Remove

- [ ] Default content
- [x] Blog

## Fix

- [ ] Broken Links (`yarn build`)
